/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladorffl;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author fredyalejandrogutierrezvelasquez
 */
public final class fmrCompilador extends javax.swing.JFrame {

    listaCapturaDato xLineaConsola;

    /**
     * Creates new form fmrCompilador
     */
    public fmrCompilador() {
        initComponents();

        cargarTxt("/Users/fredyalejandrogutierrezvelasquez/Documents/ProgramasJava/CompiladorFFL/Programa.txt");
        this.xLineaConsola = new listaCapturaDato();

        ///ABRIR ARCHIVO
        JMenuItem menuAbrir = new JMenuItem("Abrir");
        menuAbrir.addActionListener((ActionEvent e) -> {
            cargarDatos();
        });
        jMenu3.add(menuAbrir);

        ///GUARDAR ARCHIVO
        JMenuItem menuGuardar = new JMenuItem("Guardar");
        menuGuardar.addActionListener((ActionEvent e) -> {
            guardarDatos();
        });
        jMenu3.add(menuGuardar);

        ///COPIAR TEXTO
        JMenuItem menuCopiar = new JMenuItem("Copiar");
        menuCopiar.addActionListener((ActionEvent e) -> {
            this.txtCodigoFuente.copy();
        });
        jMenu5.add(menuCopiar);

        ///CORTAR TEXTO
        JMenuItem menuCortar = new JMenuItem("Cortar");
        menuCortar.addActionListener((ActionEvent e) -> {
            this.txtCodigoFuente.cut();
        });
        jMenu5.add(menuCortar);

        ///PEGAR TEXTO
        JMenuItem menuPegar = new JMenuItem("Pegar");
        menuPegar.addActionListener((ActionEvent e) -> {
            this.txtCodigoFuente.paste();
        });
        jMenu5.add(menuPegar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigoFuente = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        statusMsg2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDatoConsola = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtErrores = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código fuente");

        txtCodigoFuente.setColumns(20);
        txtCodigoFuente.setForeground(new java.awt.Color(0, 102, 51));
        txtCodigoFuente.setRows(5);
        jScrollPane1.setViewportView(txtCodigoFuente);

        jLabel2.setText("Errores");

        jLabel3.setText("Compilador");

        statusMsg2.setText("Estado");
        statusMsg2.setToolTipText("");

        jLabel5.setText("Dato consola:");

        txtDatoConsola.setEnabled(false);
        txtDatoConsola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDatoConsolaKeyPressed(evt);
            }
        });

        jButton1.setText("Asignar");
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        txtConsola.setEditable(false);
        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane4.setViewportView(txtConsola);

        txtErrores.setEditable(false);
        txtErrores.setColumns(20);
        txtErrores.setForeground(new java.awt.Color(255, 51, 0));
        txtErrores.setRows(5);
        jScrollPane3.setViewportView(txtErrores);

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Token", "Línea", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tblDatos);

        jMenu3.setLabel("Archivo");
        jMenuBar2.add(jMenu3);

        jMenu5.setLabel("Editar");
        jMenuBar2.add(jMenu5);

        jMenu7.setText("Validar");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Compilar");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu8);

        jMenu10.setText("Quienes somos");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusMsg2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatoConsola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(355, 439, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDatoConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusMsg2)
                .addContainerGap())
        );

        statusMsg2.getAccessibleContext().setAccessibleName("statusMsg2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Copia texto de textbox al clipboard
     *
     * @param evt
     */
    private void copiarTexto(java.awt.event.MouseEvent evt) {
        this.txtCodigoFuente.copy();
    }

    /**
     * Metodo utilizado para iniciar analizado de programa
     *
     * @param evt
     */
    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        this.jMenu8.setEnabled(false);
        compilar(false);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (!"".equals(this.txtDatoConsola.getText().trim())) {
            this.xLineaConsola.agregarDato(this.txtDatoConsola.getText());
            this.txtDatoConsola.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Debe indicar un dato valido");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * Metodo utilizado para cargar datos del textbox a hilo de la consola
     *
     * @param evt
     */
    private void txtDatoConsolaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoConsolaKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!"".equals(this.txtDatoConsola.getText().trim())) {
                this.xLineaConsola.agregarDato(this.txtDatoConsola.getText());
                this.txtDatoConsola.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Debe indicar un dato valido");
            }
        }
    }//GEN-LAST:event_txtDatoConsolaKeyPressed

    /**
     * Metodo utilizado para mostrar datos del compilador
     *
     * @param evt
     */
    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        JOptionPane.showMessageDialog(null, "UNIVERSIDAD CENTRAL\n Estudiantes: \nFredy Gutierrez \nFredy Guacaneme \nLeonardo Sanchez \nVersión: 21052019");
    }//GEN-LAST:event_jMenu10MouseClicked

    /**
     * Ejecuta proceso para realizar una validación previa al lenguaje
     * @param evt 
     */
    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        compilar(true);
    }//GEN-LAST:event_jMenu7MouseClicked

    /**
     * Metodo encargado de suncronizar los pasos del compilador
     *
     * @param n
     */
    public synchronized void sincroPasoAPaso(javax.swing.AbstractListModel n) {
        this.txtConsola.setText("");
        for (int i = 0; i < n.getSize(); i++) {
            this.txtConsola.setText(this.txtConsola.getText() + "\n" + (String) n.getElementAt(i));
        }
    }

    /**
     * Sincroniza paso a paso con el compiladors
     *
     * @param n
     */
    public synchronized void sincroErrores(javax.swing.AbstractListModel n) {
        this.txtErrores.setText("");
        for (int i = 0; i < n.getSize(); i++) {
            this.txtErrores.setText(this.txtErrores.getText() + "\n" + (String) n.getElementAt(i));
        }
    }
    
    /**
     * Elimina filas de JTable para reiniciar los simbolos
     * @param tabla 
     */
    public void limpiarTabla(javax.swing.JTable tabla){
        try {
            javax.swing.table.DefaultTableModel modelo=(javax.swing.table.DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    
    /**
     * Sincroniza simbolos
     *
     * @param n
     */
    public synchronized void sincroSimbolos(ArrayList<compilador.itemSimbolos> n) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)this.tblDatos.getModel();
        for (int i = 0; i < n.size(); i++) {
            Object []object = new Object[3];
            object[0] = n.get(i).get_Linea();
            object[1] = n.get(i).get_Token();
            object[2] = n.get(i).get_Tipo().toString();
            modelo.addRow(object);    
        }
    }

    /**
     * Sincroniza opción de menu de compilador
     *
     * @param n
     */
    public synchronized void habilitarCompilador(boolean n) {
        this.jMenu8.setEnabled(n);
    }

    /**
     * Sincroniza opción de menu de compilador
     *
     * @param n
     */
    public synchronized void habilitarConsola(boolean n) {
        this.txtDatoConsola.setEnabled(n);
        this.jButton1.setEnabled(n);
    }

    /**
     * Sincroniza paso a paso con el compilador
     *
     * @return
     */
    public synchronized String getDato() {
        String xDato = this.txtDatoConsola.getText();
        this.txtDatoConsola.setText("");
        this.txtDatoConsola.setEnabled(false);
        return xDato;
    }

    /**
     * Compilar
     * @param xSoloValida
     */
    public void compilar(boolean  xSoloValida) {
        ///LIMPIAR
        limpiarTabla(this.tblDatos);
        this.txtErrores.setText("");
        this.txtConsola.setText("");

        java.util.List<String> xDatosArchivo = new ArrayList<>();
        String[] xTexto = this.txtCodigoFuente.getText().split("\n");
        xDatosArchivo.addAll(Arrays.asList(xTexto));
        this.objCompilador = new compilador(this, this.xLineaConsola);
        this.objCapturaDatoConsola = new listaCapturaDato();
        this.objCompilador.setPasosCompilador(xDatosArchivo);
        this.objCompilador.setSoloValidar(xSoloValida);
        this.objCompilador.start();
    }

    /**
     * Guardar datos de codigo fuente
     */
    public void guardarDatos() {
        String Text = "";
        try {
            JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
            fc.showSaveDialog(this);
            File Guardar = fc.getSelectedFile();
            if (Guardar != null) {
                FileWriter Guardx = new FileWriter(Guardar);
                Guardx.write(this.txtCodigoFuente.getText());
                Guardx.close();
            }
        } catch (IOException ioe) {
            System.out.println(ioe);
        }
    }

    /**
     * Cargar archivo txt por openfiledialog
     */
    public void cargarDatos() {
        JFileChooser chooser;
        chooser = new JFileChooser();
        int sel = chooser.showOpenDialog(this.txtCodigoFuente);
        if (sel == chooser.APPROVE_OPTION) {
            File selFile;
            selFile = chooser.getSelectedFile();
            cargarTxt(selFile.getAbsolutePath());
        }
    }

    /**
     * Carga contenido de txt
     *
     * @param xArchivo
     */
    private void cargarTxt(String xArchivo) {
        statusMsg2.setText("abriendo " + xArchivo);
        String linea;
        try {
            FileReader fr = new FileReader(xArchivo);
            BufferedReader entArch = new BufferedReader(fr);
            linea = entArch.readLine();
            txtCodigoFuente.setText("");
            while (linea != null) {
                txtCodigoFuente.setText(txtCodigoFuente.getText() + linea + "\n");
                linea = entArch.readLine();
            }
            entArch.close();
            txtCodigoFuente.setForeground(Color.red);
        } catch (IOException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmrCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmrCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmrCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmrCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmrCompilador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel statusMsg2;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextArea txtCodigoFuente;
    private javax.swing.JTextArea txtConsola;
    private javax.swing.JTextField txtDatoConsola;
    private javax.swing.JTextArea txtErrores;
    // End of variables declaration//GEN-END:variables
    private compilador objCompilador;
    private listaCapturaDato objCapturaDatoConsola;
}
